defaults:
  - model_checkpoint.yaml
  - early_stopping.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: checkpoints
  filename: "epoch_{epoch:03d}_{step:03d}"
  monitor: "val/acc"
  mode: "max"
  save_last: True
  every_n_train_steps: 20
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/acc"
  patience: 100
  mode: "max"
